### PR TITLE
Add Class Game that contains the logic

### PR DESCRIPTION
**Pull request by c-m-a**
Add game class to lib directory

Class Game Methods
- initialize
- over?
- check_winner
- check_rows
- check_columns
- check_diagonals

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Awesome game :+1: 
I enjoyed playing your game. The interface is cool. I almost approved it but found only one bug that needs fixing before we can merge.
Your game does not display when it's a draw but instead, a new game is started.
draw
I expected a draw after typing 6 but instead, it takes that as the name of the first player. Please fix that and send it for another review.

### Martin Afani

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great progress @cma4c :clap: :clap: However, the game doesn't cope well with some cases. also I have some suggestions regarding the oop design that you've applied. check :arrow_down: 

##### Behaviour 

- **[REQUIRED]** The application can determine if move is a winning move
  - After 8 moves the game stops and shows a tie result :warning: 
image

- **[REQUIRED]** The application can tell if there was a draw after players move
  - same problem after 8 moves

##### Implementation details

* [x] The project uses at least two classes (Usually it uses three: Game, Board and Player). The code of the project should be logically divided between classes. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/classes.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
  - Think of decoupling the game into concepts that can be translated into objects (classes) that communicate between each others through messages (methods).
* [x] All classes are kept in `lib` directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [x] The code should respect the single responsibility rule for methods (i.e. each method does exactly one thing). Student's tends to create long methods that are doing multiple steps of the game process. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/single_responsibility.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [x] Use attr_readers/attr_writers instead of attr_accessors. The student must be aware that by using it they allow writing that property from outside the class. That variable can be set to anything. <TODO: explain why> ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/attr_accessor.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [x] DRY rule should be respected. E.g. students tend to check winning position for X and O separately instead of creating a method and reuse it. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/dry.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

### That's it :relieved: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by c-m-a** [comment]
>     * hrough messages (methods).

But I coded the game base on one class, that makes me think that it's better to start coding the objects that the view. Now I have to change many things of the code. :(

**Comment by stratospherique** [comment]
Hi @cmac4
I know that the idea of implementing these suggestions seems overwhelming. However, based on your code, it's not a hard task, you just need to relax and give it try. Notice that this project is a good exercise to learn and apply oop principals which you will encounter often in the future as a developer.

**Comment by Anna-Myzukina** [comment]
### Your project looks :+1:  good!
### Great job thus far.

But now it seems that it works not correct, please check your game.

When the user chooses position 1, the game congrats "You win!" & stop. I tested it a few times:



When user chooses position 1 & 2, game congrats "You win!" & stop


When the user chooses position 3, the game congrats "You win!" & stop


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project still needs changes

**Comment by c-m-a** [comment]
> The project still needs changes

I checked the game in my machine but It didn't show the same errors from the images!

**Comment by c-m-a** [comment]
I think you downloaded the development branch!

**Review by whiz25 — APPROVED** [review]
## Awesome @cma4c :clap: 
You have made all the required changes and now your app works as expected. It's a :+1: from me. Merge and proceed.

### Martin Afani

**Pull request merged**
