### PR TITLE
Build User interface

### PR DESCRIPTION
**Pull request by c-m-a**
- Added players' name section.
 - Added Game's status.
 - Added Position selector section.

### CODE REVIEW

**Comment by shshamim63** [comment]
## Status :recycle: [!! Required Changes !!] :recycle: 
___
Hi @cma4c  :wave,
Great initiative :clap: . I can see summary on the PR which reflect about the task you have covered in here. Awesome :sunglasses: .
But there are some issues that are actually blocking me declare this milestone as complete :disappointed: . But the main thing is , by the pace of your work I am sure that you will cover all the mentioned issue to earn the ultimate goal for this milestone :smile: .
___
#### Please follow the instructions below :point_down: to complete the milestone.
___
### :spades: [Mandatory Changes] :spades: 
___
1. It should inform player if selected move is a winning move.
images
2. Should inform player if selected move is a draw move.
___
### :clubs: [Optional Changes] :clubs:
___
:warning: You got about 109 lines of code in main.rb. But the commit number to cover is just one. I think there could be some adequate number of commit in here. Please apply more commits on your next milestones.
1. You can divide the rendering messages into several functions. Cause A while loop containing massive amount of code is actually reducing the readability. instead if that contains some block of methods, it will definitely gain its readability.
2. I can see you can ignored the bin folder in your stickler.yml
https://github.com/cma4c/tic-tac-toe-ruby/blob/cbafd3956fd641008b90e6d4c4e26d0e1ed1c9a2/.stickler.yml#L10
It is upto you. 

___
#### Please follow the instructions above and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](__Shakhawat Hossain__)

**Comment by Anna-Myzukina** [comment]
#### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Your project looks :+1:  good!
### Great job thus far. Please fix Lint errors before it can be approved.


Great that you are added README file image
* Please remember that readme file should be descriptive.
screen
 I hope these links can help make it  [Professional Github repository](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) and this [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).

* And maybe it`s not a bad idea to add any message if player choose the same move :) 
pol

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project has Linter errors

**Comment by Anna-Myzukina** [comment]
## Hi! image

### Please fix Lint errors before it can be approved.




### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project has Linter errors

**Comment by c-m-a** [comment]
> The project has Linter errors

I know! but I refactored some lines, I prefer that you give me some refactor suggestion When I send a pull request because it doesn't make sense for me to see the same message that Rubocop shows me! :|

**Review by whiz25 — CHANGES_REQUESTED** [review]
## good job team :+1: 
You are almost done with this project but you have one thing to fix, Linting errors.
Please do that and submit for another review.

### Martin Afani

**Review by whiz25 — APPROVED** [review]
## Awesome :+1: 
Everything looks good for this milestone. Merge and proceed.

### Martin Afani

**Pull request merged**
